version: '3.5'

networks:
  load-testing-network:
    external: true

services:
  influxdb:
    container_name: influxdb-performance
    image: influxdb:1.8.9
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    networks:
      - load-testing-network

  grafana:
    container_name: grafana-performance
    image: grafana/grafana:latest
    ports:
      - "3300:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ../grafana/dashboards:/var/lib/grafana/dashboards
      - ../grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ../grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    networks:
      - load-testing-network